### ISSUE TITLE
Failed to execute goal on project topology-common

### ISSUE THREAD

**Issue by nitishkv** [ahassany/topology-service#13]
I am getting following error:

"Failed to execute goal on project topology-common: Could not resolve dependencies for project net.es:topology-common:jar:0.1.0-SNAPSHOT: Failure to find net.es.lookup:lookup-service-client:jar:0.1 in https://repo.maven.apache.org/maven2 was cached in the local repository"

Please let me know, how to solve above problem

**Comment by ahassany** [comment]
This project is currently unmaintained.

See https://github.com/ahassany/topology-service/wiki/Using-NML-NSI-Topology-Service for how to install the dependency on net.es.lookup:lookup-service-client. Though if recall correctly, this project moved from Google Code hosting to github.
